- README.md
After Node 6 failed for me, I noticed that you changed the requirements to Node 7 in the travis.yml - once I upgraded to Node 7 everything worked.
> Documentation Update: Node 7 Required

- src/mutations/story.js
The length validator for the `text` field was looking at `input.url` instead of `input.text`. This updates the validator to use the appropriate field.
> Fix story mutation validation

- src/schema/CommentType.js
Demo graphiql returns the error based on seed data.
```javascript
{
"message": "Cannot read property 'load' of undefined",
"locations": [
{
"line": 14,
"column": 9
}
],
"path": [
"stories",
"edges",
0,
"node",
"comments"
]
}
```
I think comment could have no parent if it's a parent comment.
> fix: parent comment might not exist

- migrations/201612010000_initial.js
- src/Context.js
- src/passport.js
- src/schema/EmailType.js
- src/schema/Node.js
- src/schema/UserType.js
The `users.emails` JSONB field is now deprecated in favor of a separate table for storing users' email addresses:
```js
await db.schema.createTable('emails', table => {
table.uuid('id').notNullable().defaultTo(db.raw('uuid_generate_v1mc()')).primary();
table.uuid('user_id').notNullable().references('id').inTable('users').onDelete('CASCADE').onUpdate('CASCADE');
table.string('email', 100).notNullable();
table.boolean('verified').notNullable().defaultTo(false);
table.boolean('primary').notNullable().defaultTo(false);
table.timestamps(false, true);
table.unique(['user_id', 'email', 'verified']);
});
```
> Replace users.emails JSONB field with emails table

- api/package.json
- api/schema.graphql
- db/package.json
- package.json
Move workspace related global scripts from the top-level `package.json` into `package.json` inside of workspaces.
> Define global scripts per workspace

- .pnp.js
- .vscode/settings.json
- api/package.json
- db/package.json
- db/scripts/backup.js
- db/scripts/psql.js
- db/scripts/reset.js
- db/scripts/restore.js
- yarn.lock
- Replace [`child_process.spawn`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) with [`cross-spawn`](https://github.com/moxystudio/node-cross-spawn) (for better compatability with Windows).
- Drop existing connections before dropping the database via `yarn db:reset` (see `scripts/reset.js`).
> Replace child_process.spawn with cross-spawn

- api/schema.graphql
- api/src/context.ts
- api/src/error.ts
- api/src/index.ts
- api/src/mutations/story.ts
- api/src/utils/__snapshots__/validator.test.ts.snap
- api/src/utils/index.ts
- api/src/utils/validator.test.ts
- api/src/utils/validator.ts
- Improve generics usage in `validate(input, x => ...)` utility function, add some unit tests
- Move it from `src/validator.ts` to `src/utils/validator.ts`
- Remove `ctx.validate(input, ...)` in favor of calling this helper function directly
- Move validation errors to mutation payloads. For example:
```js
import { validate } from "../utils";
// ...
async mutateAndGetPayload(input, ctx: Context) {
// Validate and sanitize user input
const { data, errors } = validate(input, (x) =>
x
.field("title", { trim: true })
.isRequired()
.isLength({ min: 5, max: 80 })
.field("text", { alias: "URL or text", trim: true })
.isRequired()
.isLength({ min: 10, max: 1000 }),
);
if (errors.length > 0) {
return { errors };
}
// ...
}
```
```graphql
mutation {
upsertStory(input: { title: "test" }) {
story { …
```
> Move validation errors to mutation payloads

- api/src/index.ts
- api/src/session.ts
```js
import { session } from "./session"; // previously import { auth } from "./auth";
const api = new Router();
api.use(session);
```
> Rename "auth" middleware to "session"

- api/scripts/deploy.ts
- env/index.cjs
```bash
$ yarn deploy              # Same as `yarn deploy --env=dev`
$ yarn deploy --env=dev    # Deploys gs://pkg.example.com/api_{version}.zip to https://example.com
$ yarn deploy --env=test   # Deploys gs://pkg.example.com/api_{version}.zip to https://test.example.com
$ yarn deploy --env=prod   # Deploys gs://pkg.example.com/api_{version}.zip to https://dev.example.com
```
> Fix --env not working with `yarn deploy`

- .eslintrc.js
- .pnp.js
- .prettierrc.js
- api/babel.config.js
- api/package.json
- api/src/auth/connect.ts
- db/package.json
- env/package.json
- package.json
- proxy/package.json
- proxy/webpack.config.js
- yarn.lock
- Move ESLint configuration from `package.json` to `.eslintrc.js` as it grows in size
- Add more default settings to ESLint configuration
- List all ESLint ignore rules in one place `.eslintrc.js` -> `ignoreSettings`
- Move Prettier configuration to `.prettierrc.js` in order to match ESLint configuration approach
- Move `package.json->private` setting to the top, right after `package.json->version`
> Add .eslintrc.js to the root

- .pnp.js
- .vscode/settings.json
- babel.config.js
- env/.env
- env/index.cjs
- proxy/bindings.d.ts
- proxy/main.ts
- proxy/package.json
- proxy/parse.test.ts
- proxy/parse.ts
- proxy/tsconfig.json
- proxy/webpack.config.js
- scripts/build-api.js
- scripts/deploy-proxy.js
- yarn.lock
- Add unit tests to `proxy` workspace
- Rename Cloudflare environment variables to match Terraform
- `CF_ACCOUNT_ID` => `CLOUDFLARE_ACCOUNT_ID`
- `CF_ZONE_ID` => `CLOUDFLARE_ZONE_ID`
- `CF_TOKEN` => `CLOUDFLARE_API_TOKEN`
- Export `load(envName)` function from `env` module
- Update `proxy` module to handle URLs such as
- `https://example.com`
- `https://test.example.com` - test / QA deployment
- `https://123-test.example.com` - review deployment per PR, where 123 is the PR number
- Improve `proxy` deployment script
> Application routing via Cloudflare Workers

- api/README.md
- scripts/bundle-web.js
- scripts/deploy-web.js
- scripts/package.json
- web/README.md
- web/package.json
- web/pages/index.tsx
- web/server.js
- yarn.lock
Add `yarn build`, `yarn push`, and `yarn deploy` scripts to the `web` (Next.js) project that deploys the app to Google Cloud Functions (GCF). Also, update Relay from `10.1.2` to `10.1.3`.
Compile and bundle the code into the `dist/web.zip` file (`yarn build`), upload
it to Google Cloud Storage (`yarn push`), and finally, deploy or re-deploy
the Google Cloud Function straight from GCS (`yarn deploy`).
```
$ yarn web:build
$ yarn web:push [--version=#0]
$ yarn web:deploy [--version=#0] [--env=#1]
```
**NOTE**: These three separate steps are necessary in order to optimize the CI/CD
workflows (see `.github/workflows`).
> Add `yarn deploy` script for "web"

- README.md
- web/common/App.tsx
- web/core/relay.ts
- web/core/router.ts
- web/main.tsx
- web/proxy/index.ts
- web/proxy/transform.ts
- web/public/index.html
When an HTML page is being served from CDN edge locations via Cloudflare Workers (see `proxy/index.ts`, `proxy/transform.ts`), it injects the serialized API response (Relay store) such as:
```html
<script id="data" type="application/json">
{
"client:root": {
"__id": "client:root",
"__typename": "__Root",
"me": { id: "123", name: "John", email: "john@example.com" }
}
}
</script>
```
Once the app is being bootstrapped on the client-side (in the browser), this data is being deserialized and passed into the Relay client.
```tsx
// Dehydrate the initial API response and initialize a Relay store
const data = document.getElementById("data")?.innerHTML.trim();
const records = data ? JSON.parse(data) : undefined;
const relay = createRelay({ records });
// Render the top-level React component …
```
> Hydrate / dehydrate GraphQL API query response

- api/auth/connect.ts
- api/context.ts
- api/mutations/auth.ts
- api/mutations/user.ts
- api/queries/user.ts
- api/session.ts
- api/utils/id.ts
- api/utils/username.ts
- db/migrations/001_initial.js
- db/scripts/repl.js
- db/scripts/update-types.js
- db/seeds/00_reset.js
- db/seeds/01_users.js
Update sample database schema and `update-types` script to use singular names for database tables.
- `users` -> `user`
- `identities` -> `identity`
It's a bit more practical. You can run `yarn db:reset` to migrate the actual db schema after pulling this update.
> Prefer singular database table names

- README.md
- env/.env.dev
- env/.env.local
- env/.env.prod
- env/.env.test
- img/README.md
- img/index.js
- img/package.json
- package.json
- scripts/deploy-img.js
- setup.js
- web/common/App.tsx
- web/proxy/index.ts
- yarn.lock
This cloud function is intended to be used for image resizing and optimization
needs as a light and cheaper alternative to 3rd party services.
```js
const { createHandler } = require("image-resizing");
/**
* Dynamic image resizing. Usage example:
*
*   https://example.com/img/image.jpg - original image
*   https://example.com/img/w_60,h_80/image.jpg - 60x80 thumbnail
*
* @see https://github.com/kriasoft/image-resizing
*/
module.exports.img = createHandler({
// Where the source images are located.
// E.g. gs://s.example.com/image.jpg
sourceBucket: process.env.SOURCE_BUCKET,
// Where the transformed images needs to be stored.
// E.g. gs://c.example.com/image__w_80,h_60.jpg
cacheBucket: process.env.CACHE_BUCKET,
});
```
Ensure that the source and cache GCS bucket exist, then run:
```
$ yarn …
```
> [img] Cloud image resizing (GCF)

- db/README.md
- db/scripts/reset.js
- db/seeds/02_identities.js
- web/core/router.types.ts
Fix `--env` flag not working correctly with `yarn db:reset` script:
`$ yarn db:reset [--env #0]` - Resets database schema and re-applies all the migrations
`$ yarn db:reset [--env #0] [--seed]` - Resets database schema and seeds it with sampel/reference data
`$ yarn db:reset [--env #0] [--from #0]` - Resets database schema and restore data from the backup
Where `--env #0` is the target environment such as `local`, `dev` (default), `test`, or `prod`.
While `--from #0` is the source environment for which the backup file was created (via `yarn db:backup [--env #0]`).
> [db] Fix --env flag in db:reset script

- .yarnrc.yml
- README.md
- api/email.ts
- api/emails/welcome/html.hbs
- api/emails/welcome/subject.hbs
- api/env.ts
- api/package.json
- env/.env.dev
- env/.env.local
- env/.env.prod
- env/.env.test
- package.json
- scripts/deploy-api.js
- yarn.lock
- Integrate [`email-templates`](https://github.com/forwardemail/email-templates) pre-configured with:
- [`Nodemailer`](https://nodemailer.com/) for sending transactional emails (via SMTP, Sendgrid, Postmark, etc.)
- [`Handlebars`](https://handlebarsjs.com/), [`juice`](https://github.com/Automattic/juice) for email templates
- [`i18n`](https://github.com/ladjs/i18n) for email template localization
- [`preview-email`](https://github.com/forwardemail/preview-email) for previewing emails in the browser, great for development and debugging
- Add `EMAIL_FROM`, `EMAIL_PASSWORD` environment variables
```ts
import email from "../email";
await email.send({
template: "welcome",
message: {
to: "john@example.com",
},
locals: {
name: "John"
}
});
```
Find email templates in the …
> [api] Email templates; email sender

- api/context.ts
- api/core/logging.ts
- api/env.ts
- api/errors.ts
- api/graphql.ts
- api/mutations/resetPassword.ts
- api/package.json
- scripts/api-deploy.js
- scripts/img-deploy.js
- yarn.lock
- Tweak the logging compatibility with Google Cloud Functions (2nd gen)
- Let Google Error Reporting pick up log messages and errors from `stdin` / `stdout` as a simple solution
- Add `ctx.log(...)` helper function to `Context` available from GraphQL resolver functions
- Exclude Node.js native modules and Express related stuff from the error stack traces in development mode
```typescript
{
type: UserType,
resolve(self, args, ctx) {
ctx.log("INFO", "Fetching user account.");
try {
/* .... */
} catch (err) {
ctx.log("ERROR", err);
}
}
}
```
or, from anywhere within the Node.js/Express app:
```typescript
import { log } from "./core";
app.get("/example", (req, res) => {
log(req, res, "INFO", "Hello from Express app.");
...
});
```
**Reference** …
> [`api`] Logging and error reporting

- .github/workflows/pull_request.yaml
- api/index.ts
- api/queries/users.ts
- api/tests/fetch-user.test.ts
- env/.prod.env
- env/.test.env
- package.json
- setup.js
- Update Jest configurations to use `projects`
- Pre-load environment variables (from `env/.local.env` file) when running tests (using [`envars`](https://github.com/kriasoft/envars#readme))
- Transpile ESM code to CommonJS since Jest doesn't yet support ESM natively: facebook/jest#4842 including a couple of ESM-only Node.js modules such as `got`
- Add an integration test example using [Jest](https://jestjs.io/) and [Supertest](https://github.com/visionmedia/supertest) /w  inline [snapshots](https://jestjs.io/docs/snapshot-testing)
- Add PostgreSQL service to GitHub Actions workflow (here)
```ts
import request from "supertest";
import { api, db } from "../index";
test(`fetch user(username: "test01")`, async () => {
const res = await request(api)
.post("/api")
.send({
query: `#graphql
query …
```
> [`api`] Add integration tests using Jest and Supertest

- .vscode/api.code-snippets
- .vscode/extensions.json
- .vscode/settings.json
- api/auth/session.ts
- api/context.ts
- api/core/logging.ts
- api/errors.ts
- api/graphql.ts
- db/README.md
- db/package.json
If you're using `import { log } from "./core"` directly (as opposed `ctx.log(...)`), the `res` argument is now ommited:
```ts
import { log } from "../core";
// BEFORE
log(req, res, "WARNING", "Some text or object");
// AFTER
log(req, "WARNING", "Some text or object")
```
When used inside GraphQL type resolvers, nothing has changed:
```ts
async resolve(self, args, ctx) {
ctx.log("ERROR", new Error(...));
}
```
> chore(api): Improve logging and error status code

- api/auth/facebook.ts
- api/auth/github.ts
- api/auth/google.ts
- api/auth/session.ts
- api/core/index.ts
- api/core/jwt.ts
- api/queries/me.test.ts
- Update `api/auth/session.ts` (session middleware) to allow authenticating using Google's ID token
- Move JWT related utility functions to `api/core/jwt.ts`
- Initialize Google/Facebook OAuth 2.0 clients on demand (memoize)
- Add a unit test showing how to test protected routes / API endpoints
```ts
import request from "supertest";
import { createIdToken, db } from "../core";
import { api } from "../index";
test(`fetch me (current user)`, async () => {
const res = await request(api)
.post("/api")
.auth(createIdToken({ id: "test1" }), { type: "bearer" })
.send({
query: `#graphql
query {
me { id email name }
}
`,
})
.expect(200)
.expect("Content-Type", "application/json");
expect(res.body).toMatchInlineSnapshot(`
Object {
"data": Object {
"me": Object {
"id": "VXNlcjp0ZXN0MQ==",
"email": …
```
> refactor(api): Session middleware improvements

- package.json
This PR adds the yarn 'setup' script definition back to the package.json.  I believe this was removed by mistake.
> chore: Add `yarn setup` script back to `package.json`

- api/env.ts
- api/graphql.ts
Appends `Authorization: Bearer <token>` header to requests made via GraphiQL IDE when the user is authenticated.
> feat(api): Integrate Firebase Auth into GraphiQL IDE

- app/core/auth.ts
- app/core/relay.ts
Add `getIdToken()` function that can be used outside React components. It's being used inside of Relay client like this:
```tsx
import { Environment, Network, RecordSource, Store } from "relay-runtime";
import { getIdToken } from "./auth.js";
/**
* Initializes a new instance of Relay environment.
* @see https://relay.dev/docs/
*/
export function createRelay(): Environment {
// Configure a network layer that fetches data from the GraphQL API
// https://relay.dev/docs/guides/network-layer/
const network = Network.create(async function fetchFn(operation, variables) {
const headers = new Headers({ ["Content-Type"]: "application/json" });
const idToken = await getIdToken();
// When the user is authenticated append the ID token to the request
if (idToken) {
headers.set("Authorization", `Bearer …
```
> fix(app): Authentication (ID) token in the Relay client
