README.md
=> Typo Line 5

package.json, src/app.js, yarn.lock
Closes: https://github.com/kriasoft/nodejs-api-starter/issues/14
=> Redis session store

migrations/201612010000_membership.js
Added comment to migration file on the usage of uuid_generate_v1mc when storing IDs,
=> Update 20162010000_membership.js file

.dockerignore, .travis.yml, Dockerfile, Dockerfile.dev, README.md, docker-compose.yml
=> Update Docker images; remove Docker.dev

package.json
I'd also like to take this opportunity to say that this is the best starter project in the world and you are the best human for open sourcing it!
=> Update package.json: deploy moved from bash to node

src/Context.js, src/__tests__/Context.js
```js
async resolve(parent, args, context) {
await context.ensureIsAuthenticated();
// the rest of the resolve() method
}
```
=> Add permissions example

migrations/201612010000_initial.js
Fixes a simple typo in the initial migration file.
=> Fix typo in initial migration

README.md
I've made some minor changes which I see as improvements with the Readme file, I understand if you don't agree with all the changes that I've made. Cheers! 👍
=> Update minor changes to README.md

src/schema/node.js
fix typo context.storyById -> context.commentById
=> fix: load comment by id in node.js

.prettierrc
strict prettier style configuration
=> chore: strict prettier style configuration

.gitignore, .vscode/db.code-snippets, api/src/auth.ts, db/README.md, db/migrations/001_initial.js
<p align="center"><img src="https://user-images.githubusercontent.com/197134/90134661-2aadc000-dd7a-11ea-9e66-4956f517ea95.gif" width="604" height="396" /></p>
=> Add db migration and seed code snippets

.vscode/settings.json, README.md, api/README.md, api/scripts/deploy.ts, api/src/db.ts, api/src/env.ts, api/src/index.ts, db/README.md, db/knexfile.js, env/.env, env/.env.dev, env/.env.local, env/.env.prod, env/.env.test, env/README.md, env/index.cjs, setup.js
- Add `GOOGLE_CLOUD_SQL` environment variable (Google Cloud SQL instance name)
- Update db connection settings for use with Google Cloud SQL TLS/SSL certificates
=> Update SSL settings for Cloud SQL

web/hooks/__generated__/useCurrentUserQuery.graphql.ts, web/hooks/index.ts, web/hooks/useCurrentUser.ts
Usage example:
```ts
import { useCurrentUser } from "../hooks";
export function MyComponent() {
const user = useCurrentUser();
return user === undefined
? <p>Loading...</p>
: <p>User name: {user?.name}, email address: {user?.email}</p>;
}
```
Returns `null` if the user has not been authenticated, `undefined` when the user status has not been resolved yet.
=> Add useCurrentUser() React hook

web/hooks/__generated__/useAuthSignOutMutation.graphql.ts, web/hooks/index.ts, web/hooks/useAuth.ts, web/pages/_app.tsx, web/relay/ResetRelayContext.ts, web/relay/relay.browser.ts, web/relay/relay.server.ts
```tsx
import { useAuth } from "../hooks";
export function Example(): JSX.Element {
const auth = useAuth();
return (
<React.Fragment>
<button onClick={() => auth.signIn("google")}>Sign in with Google</Button>
<button onClick={() => auth.signOut()}>Sign out</button>
</React.Fragment>
);
}
```
=> Add useAuth React hook

web/global.d.ts, web/pages/_app.tsx, web/pages/index.tsx, web/theme.ts
```tsx
import { css } from "@emotion/react";
export function Example(): JSX.Element {
return (
<div
css={(theme) => css`
color: ${theme.palette.primary};
font-family: ${theme.typography.fontFamily};
`}
/>
);
}
```
=> [web] Add Emotion theme (example)

.github/workflows/pull_request.yaml, .gitignore, README.md, setup.js
Disable Zero-install, ask to opt-in during the initial setup (`yarn setup`).
=> Ask to enable Yarn Zero-install during setup

web/common/AppToolbar.tsx, web/menu/NotificationsMenu.tsx, web/menu/index.ts
=> [web] Add Notifications menu

web/common/App.tsx, web/common/AppToolbar.tsx, web/menu/NotificationsMenu.tsx, web/menu/UserMenu.tsx, web/menu/index.ts, web/theme/index.ts
=> [web] Add Dark Mode

db/README.md, db/scripts/backup.js, db/scripts/reset.js, db/scripts/restore.js, web/common/App.tsx, web/common/AppToolbar.tsx, web/common/ErrorPage.tsx, web/core/router.ts, web/icons/Google.tsx, web/icons/index.ts, web/menu/UserMenu.tsx, web/routes/account/Settings.tsx, web/routes/home/Home.tsx, web/routes/index.ts, web/routes/user/UserProfile.tsx, web/routes/user/index.ts, web/theme/index.ts
- Fix a regression bug in `yarn db:backup [--env #0]`, `yarn db:restore [--env #0] [--from #0]`
- Add `--no-seed` argument to `yarn db:reset [--env #0] [--no-seed]`
- Remove `Container` content wrapper from the top-level `App` component
- Add Google icon to the [Sign in with Google] button
- Update page title for user profile pages
=> [db] Fix data backup and restore scripts

.gitignore, .vscode/extensions.json, .vscode/settings.json, README.md, env/.local.env, env/.prod.env, env/.test.env, infra/.terraform.lock.hcl, infra/README.md, infra/backend.tf, infra/database.tf, infra/outputs.tf, infra/providers.tf, infra/services.tf, infra/variables.tf, package.json, scripts/github.js, scripts/tf.js, web/package.json, yarn.lock
The Google Cloud Platform (GCP) and Cloudflare infrastructure resources required by the app and that can be bootstrapped via [Terraform](https://www.terraform.io/).
- [Node.js](https://nodejs.org/en/) v16+ with [Yarn](https://yarnpkg.com/) package manager
- [Google Cloud SDK](https://cloud.google.com/sdk/docs/install) and [Terraform CLI](https://learn.hashicorp.com/tutorials/terraform/install-cli)
- Access to [Google Cloud Projects](https://cloud.google.com/resource-manager/docs/creating-managing-projects) and [Terraform Cloud](https://cloud.hashicorp.com/products/terraform) workspaces
<details>
<summary>How to install Terraform CLI on macOS?</summary><br>
```bash
$ brew tap hashicorp/tap
$ brew install hashicorp/tap/terraform
$ brew update
$ brew upgrade hashicorp/tap/terraform
$ yarn tf …
```
=> Add Terraform configuration

.github/workflows/pull_request.yaml, .github/workflows/pull_request_lint.yaml, .github/workflows/push_main.yaml, package.json, scripts/postinstall.js
- Add `scripts/postinstall.js` script, that configures Husky and environment variable overrides after `yarn install`
- Add [conventionalcommits.org](https://conventionalcommits.org) PR title linting
- Update PR and Push (main) CI/CD workflows
- Add the Google Cloud SDK authentication step to CI/CD workflow
=> chore: Add postinstall script

web/common/App.tsx, web/workers/proxy.ts
```ts
export default path {
path: "/old-page",
response() {
return { redirect: "/new-page", status: 301 /* defaults to 302 */ };
}
}
```
=> fix(web): Handle redirects

api/README.md, api/context.ts, api/core/session.test.ts, api/core/session.ts, api/global.d.ts, api/mutations/README.md, api/mutations/storage-getUploadURL.ts, api/mutations/storage-saveUpload.ts, api/mutations/user-updateUser.ts, api/queries/user-me.test.ts, api/queries/user-me.ts, api/queries/user-user.test.ts, api/queries/user-user.ts, api/queries/user-users.ts, api/types/fields.ts, api/types/user.ts
```ts
import { GraphQLFieldConfig, GraphQLString } from "graphql";
import { Unauthorized, Forbidden } from "http-errors";
import { ProjectType } from "../types/project.js";
/**
* @example
*   query {
*     project(slug: "test") { id name }
*   }
*/
export const story: GraphQLFieldConfig<Project, Context> = {
type: ProjectType,
args: {
slug: { type: GraphQLString }
},
resolve(self, args, { db, token }) {
// Restrict anonymous access
if (!token) {
throw new Unauthorized();
}
// Fetch project details from Firestore
const res = await db.collection("project").where("slug", "==", args.slug).get();
const project = res.doc()[0]
// Only project authors can access a project
if (!project || project.data().authorId !== token.uid) {
throw new Forbidden();
}
return project;
}
};
```
=> refactor(api): Improve Firebase Auth integration

.vscode/launch.json, api/graphql.ts
=> fix(dev): Update VSCode debug configuration
